--Criando database
CREATE DATABASE eventoapp WITH ENCODING 'UTF8' LC_COLLATE='Portuguese_Brazil.1252' LC_CTYPE='Portuguese_Brazil.1252';

\c eventoapp

--Criando usuário da aplicação
CREATE USER eventoadmin WITH ENCRYPTED PASSWORD 'eventoadmin2021';

CREATE TABLE EVENTO (
CODIGO BIGINT PRIMARY KEY,
DATA VARCHAR (255) NOT NULL,
HORARIO VARCHAR (255) NOT NULL,
LOCAL VARCHAR (255) NOT NULL,
NOME VARCHAR (255) NOT NULL
);

CREATE TABLE CONVIDADO (
RG VARCHAR(255) PRIMARY KEY NOT NULL,
NOME_CONVIDADO VARCHAR (255) NOT NULL,
EVENTO_CODIGO BIGINT,
FOREIGN KEY (EVENTO_CODIGO) REFERENCES EVENTO(CODIGO)
);

CREATE TABLE EVENTO_CONVIDADO (
EVENTO_CODIGO BIGINT PRIMARY KEY,
CONVIDADO_RG VARCHAR (255) NOT NULL,
FOREIGN KEY (EVENTO_CODIGO) REFERENCES EVENTO(CODIGO),
FOREIGN KEY (CONVIDADO_RG) REFERENCES CONVIDADO(RG)
);

--Dando Permissões para o usuário
GRANT ALL PRIVILEGES ON DATABASE eventoapp TO eventoadmin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO eventoadmin;